#!/bin/bash
# verify-update-metadata.sh — Verify that electron-builder produced the files
# electron-updater needs to detect updates from a GitHub Release.
#
# electron-updater (GitHub provider) resolves updates by reading:
#   - latest-mac.yml  (macOS arm64/x64)
#   - latest.yml       (Windows x64)
# from the release assets. These YAML files are generated by electron-builder
# when the `publish` config is set to `provider: github`.
#
# Usage:
#   bash scripts/verify-update-metadata.sh [output-dir]
#
# Defaults to: release/

set -euo pipefail

OUTPUT_DIR="${1:-release}"

echo "=== Update Metadata Verification ==="
echo "Checking: $OUTPUT_DIR"
echo

ERRORS=0

# ── 1. macOS metadata ────────────────────────────────────────────
echo "--- macOS metadata ---"
LATEST_MAC="$OUTPUT_DIR/latest-mac.yml"
if [ -f "$LATEST_MAC" ]; then
  echo "✓ Found: $LATEST_MAC"
  echo "  Content:"
  sed 's/^/    /' "$LATEST_MAC"
  echo

  # Verify it references a ZIP (not just DMG)
  if grep -q '\.zip' "$LATEST_MAC" 2>/dev/null; then
    echo "✓ References ZIP asset (required for electron-updater)"
  else
    echo "✗ No ZIP reference found in latest-mac.yml"
    echo "  electron-updater downloads ZIP for macOS updates."
    echo "  Ensure electron-builder.yml has zip target under mac.target."
    ERRORS=$((ERRORS + 1))
  fi
else
  echo "✗ Missing: $LATEST_MAC"
  echo "  electron-updater cannot detect updates without this file."
  echo "  Cause: publish.provider must be 'github' and the build must"
  echo "  complete a non-directory target (dmg or zip)."
  ERRORS=$((ERRORS + 1))
fi
echo

# ── 2. Windows metadata ──────────────────────────────────────────
echo "--- Windows metadata ---"
LATEST_YML="$OUTPUT_DIR/latest.yml"
if [ -f "$LATEST_YML" ]; then
  echo "✓ Found: $LATEST_YML"
  echo "  Content:"
  sed 's/^/    /' "$LATEST_YML"
else
  echo "⊘ Not found: $LATEST_YML (expected if Windows build not run)"
fi
echo

# ── 3. ZIP artifacts ─────────────────────────────────────────────
echo "--- ZIP artifacts ---"
MAC_ZIP_COUNT=$(find "$OUTPUT_DIR" -maxdepth 1 -name '*.zip' -path '*mac*' 2>/dev/null | wc -l | tr -d ' ')
if [ "$MAC_ZIP_COUNT" -gt 0 ]; then
  echo "✓ Found $MAC_ZIP_COUNT macOS ZIP file(s):"
  find "$OUTPUT_DIR" -maxdepth 1 -name '*.zip' -path '*mac*' -exec ls -lh {} \; 2>/dev/null | sed 's/^/    /'
else
  echo "✗ No macOS ZIP files found in $OUTPUT_DIR"
  echo "  electron-updater requires a ZIP asset for macOS updates."
  echo "  Run: pnpm package:mac:release"
  ERRORS=$((ERRORS + 1))
fi
echo

# ── 4. YAML ↔ filename consistency ───────────────────────────────
echo "--- YAML ↔ filename consistency ---"
if [ -f "$LATEST_MAC" ]; then
  # Extract the url field from latest-mac.yml
  YAML_URL=$(grep 'url:' "$LATEST_MAC" | head -1 | awk '{print $NF}' | tr -d '"')
  if [ -n "$YAML_URL" ]; then
    echo "  YAML url field: $YAML_URL"
    # Check if a file with that exact name exists
    if [ -f "$OUTPUT_DIR/$YAML_URL" ]; then
      echo "✓ File exists: $OUTPUT_DIR/$YAML_URL"
    else
      # Check for the space-variant (electron-builder generates spaces in filenames)
      SPACE_VARIANT=$(echo "$YAML_URL" | sed 's/CrossPDF-Studio/CrossPDF Studio/')
      if [ -f "$OUTPUT_DIR/$SPACE_VARIANT" ]; then
        echo "✗ Mismatch: YAML references '$YAML_URL' but file is '$SPACE_VARIANT'"
        echo "  Fix: cp \"$OUTPUT_DIR/$SPACE_VARIANT\" \"$OUTPUT_DIR/$YAML_URL\""
        echo "  Or rename before uploading to GitHub Release."
        ERRORS=$((ERRORS + 1))
      else
        echo "✗ ZIP referenced in YAML not found: $YAML_URL"
        echo "  Neither '$YAML_URL' nor '$SPACE_VARIANT' exists in $OUTPUT_DIR"
        ERRORS=$((ERRORS + 1))
      fi
    fi
  else
    echo "⚠ Could not extract url field from latest-mac.yml"
  fi
else
  echo "⊘ Skipping (latest-mac.yml missing)"
fi
echo

# ── 5. DMG artifacts ─────────────────────────────────────────────
echo "--- DMG artifacts ---"
MAC_DMG_COUNT=$(find "$OUTPUT_DIR" -maxdepth 1 -name '*.dmg' 2>/dev/null | wc -l | tr -d ' ')
if [ "$MAC_DMG_COUNT" -gt 0 ]; then
  echo "✓ Found $MAC_DMG_COUNT DMG file(s):"
  find "$OUTPUT_DIR" -maxdepth 1 -name '*.dmg' -exec ls -lh {} \; 2>/dev/null | sed 's/^/    /'
else
  echo "⊘ No DMG files (optional — ZIP is the update asset)"
fi
echo

# ── 6. Version consistency ───────────────────────────────────────
echo "--- Version consistency ---"
PKG_VERSION=$(node -p "require('./package.json').version" 2>/dev/null || echo "unknown")
echo "  package.json version: $PKG_VERSION"

if [ -f "$LATEST_MAC" ]; then
  META_VERSION=$(grep '^version:' "$LATEST_MAC" | awk '{print $2}' | tr -d '"')
  echo "  latest-mac.yml version: $META_VERSION"
  if [ "$PKG_VERSION" = "$META_VERSION" ]; then
    echo "✓ Versions match"
  else
    echo "⚠ Version mismatch (package.json=$PKG_VERSION, metadata=$META_VERSION)"
    echo "  This may be expected if you haven't rebuilt after a version bump."
  fi
else
  echo "⊘ Cannot check (latest-mac.yml missing)"
fi
echo

# ── 7. Publish config ────────────────────────────────────────────
echo "--- Publish config ---"
if grep -q 'provider: github' electron-builder.yml 2>/dev/null; then
  echo "✓ Publish provider: github"
else
  echo "✗ Publish provider not set to github in electron-builder.yml"
  ERRORS=$((ERRORS + 1))
fi

OWNER=$(grep 'owner:' electron-builder.yml 2>/dev/null | awk '{print $2}' | tr -d '"')
REPO=$(grep 'repo:' electron-builder.yml 2>/dev/null | awk '{print $2}' | tr -d '"')
if [ -n "$OWNER" ] && [ -n "$REPO" ]; then
  echo "✓ owner/repo: $OWNER/$REPO"
else
  echo "✗ owner/repo not set in electron-builder.yml publish config"
  ERRORS=$((ERRORS + 1))
fi
echo

# ── Summary ──────────────────────────────────────────────────────
echo "=== Summary ==="
if [ "$ERRORS" -eq 0 ]; then
  echo "✓ All update metadata checks passed."
  echo "  Ready for GitHub Release upload."
else
  echo "✗ $ERRORS issue(s) found. Fix before publishing."
  exit 1
fi
